spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://43.142.16.185:3307/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
